import { NextResponse } from "next/server";
import { listCharacters, saveCharacter } from "@/lib/persistence";
import { CharacterSchema } from "@/lib/schema";

/** GET /api/characters — list all characters */
export async function GET() {
  try {
    const characters = await listCharacters();
    return NextResponse.json(characters);
  } catch (err) {
    const message = err instanceof Error ? err.message : "Failed to list characters";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}

/** POST /api/characters — create a new character (id auto-generated from name) */
export async function POST(request: Request) {
  try {
    const body = await request.json();
    // Validate input; id is auto-generated by saveCharacter if absent
    const parsed = CharacterSchema.omit({ id: true }).parse(body);
    const character = await saveCharacter(parsed);
    return NextResponse.json(character, { status: 201 });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Failed to create character";
    return NextResponse.json({ error: message }, { status: 400 });
  }
}
