import { NextResponse } from "next/server";
import { listCharacters, saveCharacter, saveBuild, deleteCharacter } from "@/lib/persistence";
import { CharacterSchema, BuildImportedFromSchema, type Character } from "@/lib/schema";
import { characterPath } from "@/lib/persistence/paths";

/** GET /api/characters — list all characters */
export async function GET() {
  try {
    const characters = await listCharacters();
    return NextResponse.json(characters);
  } catch (err) {
    const message = err instanceof Error ? err.message : "Failed to list characters";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}

/**
 * POST /api/characters — create a new character (id auto-generated from name)
 *
 * Query parameters:
 *   withDefaultBuild=true  — atomically create a default build alongside the character.
 *     On success: 201 { character, build }.
 *     On build failure: rolls back the character file and returns 500.
 *     On rollback failure (D3): returns 500 with orphan id, path, and both error causes.
 */
export async function POST(request: Request) {
  const url = new URL(request.url);
  const withDefaultBuild = url.searchParams.get("withDefaultBuild") === "true";

  // ── Solo path — unchanged from before ────────────────────────────────────
  if (!withDefaultBuild) {
    try {
      const body = await request.json();
      // Validate input; id is auto-generated by saveCharacter if absent
      const parsed = CharacterSchema.omit({ id: true }).parse(body);
      const character = await saveCharacter(parsed);
      return NextResponse.json(character, { status: 201 });
    } catch (err) {
      const message = err instanceof Error ? err.message : "Failed to create character";
      return NextResponse.json({ error: message }, { status: 400 });
    }
  }

  // ── Composite path — character + default build, atomic rollback ───────────

  // Step 1: Parse and validate the character body
  //   Optional top-level `importedFrom` field is forwarded to the build (D19).
  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  // Extract optional importedFrom before passing to CharacterSchema (which doesn't have it)
  let importedFromData: unknown;
  if (typeof body === "object" && body !== null && "importedFrom" in body) {
    importedFromData = (body as Record<string, unknown>).importedFrom;
    // Remove it from the body before character schema parsing
    const { importedFrom: _dropped, ...charBody } = body as Record<string, unknown>;
    body = charBody;
    void _dropped;
  }

  // Validate optional importedFrom
  const importedFrom = importedFromData !== undefined
    ? BuildImportedFromSchema.safeParse(importedFromData)
    : undefined;
  if (importedFrom && !importedFrom.success) {
    return NextResponse.json(
      { error: `Invalid importedFrom: ${importedFrom.error.message}` },
      { status: 400 }
    );
  }

  const parseResult = CharacterSchema.omit({ id: true }).safeParse(body);
  if (!parseResult.success) {
    return NextResponse.json({ error: parseResult.error.message }, { status: 400 });
  }
  const parsed = parseResult.data;

  // Step 2: Save the character
  let character: Character;
  try {
    character = await saveCharacter(parsed);
  } catch (err) {
    const message = err instanceof Error ? err.message : "Failed to create character";
    return NextResponse.json({ error: message }, { status: 500 });
  }

  // Step 3: Save the default build with server-derived defaults (D4)
  //   Forward importedFrom provenance when present (D19).
  try {
    const build = await saveBuild({
      characterId: character.id,
      name: character.name,
      notes: "",
      targetItems: {},
      ...(importedFrom?.success ? { importedFrom: importedFrom.data } : {}),
    });
    return NextResponse.json({ character, build }, { status: 201 });
  } catch (buildErr) {
    const buildMessage =
      buildErr instanceof Error ? buildErr.message : "Failed to create default build";

    // Step 4: Rollback — delete the character file (D3)
    try {
      await deleteCharacter(character.id);
    } catch (deleteErr) {
      // Double failure: log both errors, surface orphan details in response (D3)
      const orphanPath = characterPath(character.id);
      console.error("[characters/route] Build creation failed:", buildErr);
      console.error("[characters/route] Rollback (deleteCharacter) also failed:", deleteErr);
      return NextResponse.json(
        {
          error: `Failed to create default build: ${buildMessage}. Rollback also failed — orphaned character id: ${character.id}, path: ${orphanPath}.`,
        },
        { status: 500 }
      );
    }

    return NextResponse.json({ error: buildMessage }, { status: 500 });
  }
}
